# Generated by Django 5.2.17 on 2026-09-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="governance",
            field=models.TextField(blank=True, verbose_name="개발 거버넌스"),
        ),
    ]
