# Generated by Django 5.2.17 on 2026-09-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0003_team_discord_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="max_uses",
            field=models.PositiveIntegerField(default=0, verbose_name="최대 사용 횟수"),
        ),
        migrations.AddField(
            model_name="organization",
            name="discord_channel_id",
            field=models.CharField(blank=True, max_length=32, verbose_name="알림 채널"),
        ),
        migrations.AddField(
            model_name="organization",
            name="discord_guild_id",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Discord 서버",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="discord_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="discord_linked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="설정"),
        ),
    ]
