# Generated by Django 5.2.17 on 2026-09-11 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        ("projects", "0003_apispec"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("login", models.CharField(max_length=100)),
                ("token_enc", models.TextField(blank=True)),
                ("refresh_enc", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_expires_at", models.DateTimeField(blank=True, null=True)),
                ("repos", models.JSONField(blank=True, default=list)),
                ("repos_checked_at", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("account_login", models.CharField(max_length=100)),
                ("account_type", models.CharField(blank=True, max_length=20)),
                ("repo_selection", models.CharField(blank=True, max_length=10)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "installed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github",
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepoConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=300)),
                ("full_name", models.CharField(max_length=200)),
                ("import_label", models.CharField(default="task", max_length=50)),
                ("assignee_default", models.CharField(default="issue", max_length=5)),
                ("auto_import", models.BooleanField(default=False)),
                ("rule_issue", models.BooleanField(default=True)),
                ("rule_branch", models.BooleanField(default=True)),
                ("rule_commit", models.BooleanField(default=True)),
                ("rule_pr", models.BooleanField(default=True)),
                ("rule_merge", models.BooleanField(default=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_id", models.CharField(max_length=64, unique=True)),
                ("occurred_at", models.DateTimeField()),
                ("kind", models.CharField(max_length=20)),
                ("actor_login", models.CharField(blank=True, max_length=100)),
                ("summary", models.CharField(max_length=200)),
                ("result", models.CharField(blank=True, max_length=100)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tasks.task",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="github.repoconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RepoIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("state", models.CharField(default="open", max_length=6)),
                ("assignee_login", models.CharField(blank=True, max_length=100)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="github.repoconnection",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="TaskGitLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.PositiveIntegerField(blank=True, null=True)),
                ("issue_title", models.CharField(blank=True, max_length=300)),
                ("issue_state", models.CharField(blank=True, max_length=6)),
                ("branch", models.CharField(blank=True, max_length=200)),
                ("pr_number", models.PositiveIntegerField(blank=True, null=True)),
                ("pr_title", models.CharField(blank=True, max_length=300)),
                ("pr_state", models.CharField(blank=True, max_length=6)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("commits", models.JSONField(blank=True, default=list)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="github.repoconnection",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="repoconnection",
            index=models.Index(fields=["full_name"], name="github_repo_full_na_e133a4_idx"),
        ),
        migrations.AddConstraint(
            model_name="repoissue",
            constraint=models.UniqueConstraint(
                fields=("connection", "number"), name="repoissue_conn_number"
            ),
        ),
    ]
