# Generated by Django 5.2.17 on 2026-09-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0001_initial"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubTeamLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_team_id", models.BigIntegerField()),
                ("slug", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github",
                        to="orgs.team",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("github_team_id",), name="githubteamlink_team_id"
                    )
                ],
            },
        ),
    ]
