# Generated by Django 5.2.17 on 2026-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0002_githubteamlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="repoissue",
            name="author_login",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="repoissue",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
