# Generated by Django 5.2.17 on 2026-09-10 06:59

from django.db import migrations, models


def clear_unverified_links(apps, schema_editor):
    apps.get_model("accounts", "User").objects.exclude(discord_user_id=None).update(
        discord_user_id=None, discord_linked_at=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_link_code",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Discord 연결 코드",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_link_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_linked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Discord 연결 시각"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="scope",
            field=models.CharField(
                choices=[
                    ("read", "읽기"),
                    ("write", "읽기·쓰기"),
                    ("bot", "Discord 봇"),
                ],
                default="read",
                max_length=5,
            ),
        ),
        # 손으로 입력한 값은 소유 증명이 없다(예전 프로필 화면). 봇이 discord id로
        # 사람을 찾는 순간 그 값은 자격증명이 되므로 검증되지 않은 값을 승격시키지 않는다.
        # 전원이 웹에서 코드를 받아 DM `연결 <코드>`를 해야 개인 DM 알림이 시작된다.
        migrations.RunPython(clear_unverified_links, migrations.RunPython.noop),
    ]
