# Generated by Django 5.2.17 on 2026-09-10 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_discordwebhook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscordWebhook",
        ),
    ]
