# Generated by Django 5.2.17 on 2026-09-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "purpose",
                    models.CharField(blank=True, max_length=200, verbose_name="목적"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "🧪 준비 중"),
                            ("on_hold", "🕓 보류 중"),
                            ("waiting", "🗂️ 대기 중"),
                            ("active", "🚧 진행 중"),
                            ("paused", "⏸️ 일시 중단"),
                            ("done", "✅ 완료"),
                            ("stopped", "🛑 정지"),
                            ("eol", "⚰️ 지원 종료"),
                        ],
                        default="preparing",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("team", "name"), name="project_team_name")
                ],
            },
        ),
    ]
