# Generated by Django 5.2.17 on 2026-09-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                ("target_date", models.DateField(verbose_name="목표일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "준비 중"),
                            ("active", "진행 중"),
                            ("done", "완료"),
                        ],
                        default="planned",
                        max_length=7,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["target_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="메모"),
                ),
                (
                    "is_blocking",
                    models.BooleanField(default=False, verbose_name="차단"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="projects.project",
                    ),
                ),
                (
                    "to_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_blocking", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_project", "to_project"), name="dependency_from_to"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("from_project", models.F("to_project")), _negated=True),
                        name="dependency_not_self",
                    ),
                ],
            },
        ),
    ]
