# Generated by Django 5.2.17 on 2026-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projectdoc"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdoc",
            name="tasks",
            field=models.ManyToManyField(blank=True, related_name="docs", to="tasks.task"),
        ),
    ]
