# Generated by Django 5.2.17 on 2026-09-16 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_projectdoc_tasks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdoc",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectdoc",
            name="updated_source",
            field=models.CharField(
                choices=[
                    ("web", "웹"),
                    ("api", "API"),
                    ("mcp", "AI"),
                    ("dc", "Discord"),
                ],
                default="web",
                max_length=4,
            ),
        ),
    ]
