# Generated by Django 5.2.17 on 2026-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectdoc_updated_by_projectdoc_updated_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="governance_extra",
            field=models.TextField(blank=True, verbose_name="프로젝트 거버넌스"),
        ),
        migrations.AddField(
            model_name="project",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="설정"),
        ),
    ]
