# Generated by Django 5.2.17 on 2026-09-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "done_when",
                    models.CharField(blank=True, max_length=300, verbose_name="완료 조건"),
                ),
                (
                    "next_action",
                    models.CharField(blank=True, max_length=200, verbose_name="다음 행동"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="진행 메모")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(default=5, verbose_name="중요도"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "시작 전"),
                            ("doing", "진행 중"),
                            ("paused", "일시정지"),
                            ("blocked", "막힘"),
                            ("review", "검토 대기"),
                            ("done", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="todo",
                        max_length=9,
                        verbose_name="상태",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="목표 기한"),
                ),
                (
                    "no_due_reason",
                    models.CharField(blank=True, max_length=200, verbose_name="기한 미정 사유"),
                ),
                (
                    "stop_reason",
                    models.CharField(blank=True, max_length=300, verbose_name="멈춘 사유"),
                ),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("doc", "문서"),
                            ("pr", "PR"),
                            ("repo", "저장소"),
                            ("other", "기타"),
                        ],
                        default="doc",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("is_done", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TodayItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("excluded", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="today_items",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="today_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("task", "task"), ("project", "project")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                ("field", models.CharField(max_length=40)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "웹"), ("api", "API"), ("mcp", "AI")],
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.apitoken",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="tasks_chang_target__8d3d06_idx",
                    ),
                    models.Index(fields=["created_at"], name="tasks_chang_created_3be81d_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["assignee", "status"], name="tasks_task_assigne_7928f6_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "status"], name="tasks_task_project_b78682_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_task_due_dat_bce847_idx"),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 1), ("priority__lte", 10)),
                name="task_priority_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "doing"), _negated=True),
                    ("due_date__isnull", False),
                    _connector="OR",
                ),
                name="task_doing_requires_due",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "blocked"), _negated=True),
                    models.Q(("stop_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="task_blocked_requires_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "done"), _negated=True),
                    ("completed_at__isnull", False),
                    _connector="OR",
                ),
                name="task_done_requires_completed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("project__isnull", False), ("task__isnull", True)),
                    models.Q(("project__isnull", True), ("task__isnull", False)),
                    _connector="OR",
                ),
                name="link_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="todayitem",
            constraint=models.UniqueConstraint(
                fields=("user", "task", "date"), name="today_user_task_date"
            ),
        ),
    ]
