# Generated by Django 5.2.17 on 2026-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="source",
            field=models.CharField(
                choices=[
                    ("web", "웹"),
                    ("api", "API"),
                    ("mcp", "AI"),
                    ("dc", "Discord"),
                ],
                max_length=4,
            ),
        ),
    ]
