# Generated by Django 5.2.17 on 2026-09-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.dates


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        ("projects", "0002_milestone_projectdependency"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="제목 없는 회의록", max_length=200, verbose_name="제목"
                    ),
                ),
                ("body_md", models.TextField(blank=True, verbose_name="본문")),
                (
                    "created_on",
                    models.DateField(default=common.dates.today_kst, verbose_name="생성일"),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="orgs.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="projects.project",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="meeting_notes", to="tasks.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on", "-id"],
            },
        ),
    ]
