# Generated by Django 5.2.17 on 2026-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingnote",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="meetingnote",
            name="created_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="회의 일시"),
        ),
    ]
